version: '3'
services:
  app:
    build:
      context: backend/app/
      dockerfile: Dockerfile.app
    container_name: app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}

    volumes:
      - ./backend/app:/app
      - static_volume:/app/static
      - static_volume:/app/media
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && poetry run start"
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis


  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - static_volume:/app/static
      - static_volume:/app/media
    depends_on:
      - app
    restart: always

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  postgres:
    container_name: postgres
    image: postgres:16-alpine3.21
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "5432:5432"



volumes:
  static_volume:
  media_volume:
