version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_app
    command: uvicorn your_project.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  static_volume:
  media_volume: